### PR TITLE
Guard against nil server image in server create/destroy

### PR DESCRIPTION
**Pull request by tdooner**
This is likely to bite if you are booting a server from a CBS volume instead of an image.

Also, I cleaned some whitespace.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @matburstorm

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by tdooner** [comment]
Hey @matburstorm, mind signing the CLA real fast so this can be merged?

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by matburstorm** [comment]
supposedly it's now signed.

Mike

**Comment by tdooner** [comment]
Great, thanks. @martinb3 or @mdarby, want to hit the big green button?

**Comment by mdarby** [comment]
WOOOO

**Comment by jjasghar** [comment]
SWEET!

:+1: :cake: :+1: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket:

**Comment by martinb3** [comment]
:+1: looks good to me. :)

**Comment by jjasghar** [comment]
Want me to release today? I think this is everyone on the call on this thread.

**Comment by martinb3** [comment]
I'm good with releasing. I think the only outstanding thing is probably the feature that precipitated the call, the one where we have a few different PRs/issues for the same thing: #95 / #104 / #105. If @mdarby and @tdooner are working on that today, maybe we should wait? Honestly whatever works -- release early, release often? :)

**Comment by jjasghar** [comment]
I'll hold off and release when everything is ready. It would be nice to have a release that catches everything everyone has been asking for, then we can move to a "faster" cadenace, and do the release early release often. I'm betting i'll end up setting up the jenkins box on RS cloud to release for us :metal:

**Comment by matburstorm** [comment]
On 07/10/2015 09:09 AM, Martin Smith wrote:
>
> I'm good with releasing. I think the only outstanding thing is 
> probably the feature that precipitated the call, the one where we have 
> a few different PRs/issues for the same thing: #95 
> <https://github.com/chef/knife-rackspace/pull/95> / #104 
> <https://github.com/chef/knife-rackspace/pull/104> / #105 
> <https://github.com/chef/knife-rackspace/pull/105>. If @mdarby 
> <https://github.com/mdarby> and @tdooner <https://github.com/tdooner> 
> are working on that today, maybe we should wait? Honestly whatever 
> works -- release early, release often? :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/chef/knife-rackspace/pull/106#issuecomment-120446791>.
>

I wanted to bring one thing up which is sort of related to this overall 
feature (eg -B). All of the other providers that I've used
that require a network based boot image (ie, SAN, eg EBS)  have the 
ability to spin the disk up in the server create itself
transparent to knife (and maybe using fog, not sure). I had to resort to 
a significant amount of hackery to create computeX and
memoryX instances that I haven't had to do for other providers I've 
used. It would be nice for the knife plugin to deal with
the complexity of creating the network boot disk, as I suspect that most 
users won't be as motivated as I was.

Mike

PS: I have the raw API code to create/reap the disks, but haven't 
investigated whether there's a more fog-gy way to do this.

**Pull request merged**
