### PR TITLE
Prefer CLI config over Knife config for locate_config_value

### PR DESCRIPTION
**Pull request by shortdudey123**

### CODE REVIEW

**Comment by shortdudey123** [comment]
@martinb3 @tas50 can you guys review and let me know if you have any feedback? thanks!

**Comment by martinb3** [comment]
I was concerned that `config` might contain a default option that we'd pick over a config file setting -- would you mind adding a test for something that has a default value, like [flavor](https://github.com/chef/knife-rackspace/blob/master/lib/chef/knife/rackspace_server_create.rb#L43-L48)? Just to be sure we don't pick a default over a config file option?

**Comment by shortdudey123** [comment]
@martinb3 working on trying to get a correct test

FWIW... this is the same think knife-ec2 has
https://github.com/chef/knife-ec2/blob/master/lib/chef/knife/ec2_base.rb#L104

**Comment by martinb3** [comment]
@shortdudey123 that's a fair point. I'll go ahead and merge and if you get a good test, feel free to open as a new PR.

**Comment by shortdudey123** [comment]
awesome, thanks!

**Pull request merged**
