### PR TITLE
Integration tests bankruptcy

### PR DESCRIPTION
**Pull request by mdarby**
I don't like doing this, but in the interest of getting this version cut... I will circle back tomorrow and start the refactoring effort, including updating these tests.

### CODE REVIEW

**Comment by martinb3** [comment]
It passes....

**Comment by martinb3** [comment]
Something makes me twitch about commenting out large swaths of code when it's under version control.

**Comment by mdarby** [comment]
I can remove them now or refactor them out this week. Up to you :)

**Comment by martinb3** [comment]
Full steam ahead. :)

**Comment by jjasghar** [comment]
https://travis-ci.org/chef/knife-rackspace/builds/71133504 looks like it's still failing?  (master branch that is)

**Comment by mdarby** [comment]
https://travis-ci.org/chef/knife-rackspace/builds/71139248 is the one that must pass (unless of course, I am wrong :))

**Comment by mdarby** [comment]
And that has seemed to have passed.

**Comment by jjasghar** [comment]
Nice, it passed: Skipping a deployment with the rubygems provider because this is not a tagged commit


But we need to tag the commit to get it pushed.

**Comment by mdarby** [comment]
on it --

**Comment by mdarby** [comment]
I've tagged master on rackspace/knife-rackspace and pushed the tag; unsure if I need to / have access to do so on the chef/knife-rackspace repo.

**Comment by martinb3** [comment]
We should be able to push tags to https://github.com/chef/knife-rackspace/tags.

**Comment by jjasghar** [comment]
i'm betting you have access to tag, go ahead and try

**Comment by jjasghar** [comment]
And you probably have to tag before the travis run to deploy?

**Comment by mdarby** [comment]
Tagged!

**Comment by mdarby** [comment]
Will nix those commented out tests and push to master to trigger another build or use another PR?

**Comment by martinb3** [comment]
It seems like it would be weird to tag before knowing if the CI passed. Maybe we can just tell it to re-run on master.

**Comment by mdarby** [comment]
I'll just restart the job and see!

**Comment by jjasghar** [comment]
@martinb3 yeah, but the problem is that the tag isnt what master is?

**Comment by martinb3** [comment]
Well, the tag is just a commit hash no? It's not specific to a branch.

**Comment by jjasghar** [comment]
true. it didn't come out how i wanted. Lets see what travis does first i guess

**Comment by martinb3** [comment]
http://i3.kym-cdn.com/photos/images/facebook/000/766/053/409.gif

**Comment by jjasghar** [comment]
boooo 

Skipping a deployment with the rubygems provider because this is not a tagged commit

**Comment by mdarby** [comment]
Wow, someone tags an untested build? :-1:

**Comment by jjasghar** [comment]
zoom?

bit.ly/zoom-jjasghar

**Comment by mdarby** [comment]
Just hitting a meeting

**Comment by jjasghar** [comment]
damn, 30 mins?

**Comment by mdarby** [comment]
y

**Comment by mdarby** [comment]
eh, nm -- on zoom now

**Comment by martinb3** [comment]
The merge commit isn't tagged. Only the previous one.

**Comment by martinb3** [comment]
Travis says: Commit ec87a39
Tag from Github says: 5a8830c

**Comment by martinb3** [comment]
Just repushed the tag with the same commit hash as Travis.

**Pull request merged**
